@startuml

title __GROUPPROJECT's Class Diagram__\n

  namespace a {
    namespace om.example {
      namespace Controllers {
        class com.example.Controllers.ConfirmingOrdersController {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example {
      namespace Controllers {
        class com.example.Controllers.CustomerInfoPageController {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example {
      namespace Controllers {
        class com.example.Controllers.EmployeeController {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example {
      namespace Controllers {
        class com.example.Controllers.ManagerController {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example {
      namespace Controllers {
        class com.example.Controllers.OrderController {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example {
      namespace Controllers {
        class com.example.Controllers.ReceiptController {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example {
      namespace Controllers {
        class com.example.Controllers.StartingController {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example {
      namespace Database {
        class com.example.Database.Database {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example {
      class com.example.DeliveryInfoObject {
      }
    }
  }
  

  namespace  {
    namespace om.example {
      class com.example.DrinkObject {
      }
    }
  }
  

  namespace  {
    namespace om.example {
      class com.example.Main {
      }
    }
  }
  

  namespace  {
    namespace om.example {
      class com.example.PizzaObject {
      }
    }
  }
  

  com.example.Main -up-|> javafx.application.Application


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
