@startuml
class com.example.Controllers.EmployeeController {
- Stage stage
- Scene scene
- Parent root
~ TextField IDTextField
~ TextField passwordTextField
~ Label employeeLoginLabel
~ Label IDLabel
~ Label passwordLabel
~ Label warningLabel
+ void switchToCustomerInfo(ActionEvent)
+ void switchToCustomerInfo()
+ {static} boolean isInteger(String)
+ void testUsernamePassword()
}
class com.example.Controllers.ManagerController {
- Stage stage
- Scene scene
- Parent root
~ TextField IDTextField
~ TextField passwordTextField
~ Label managerLoginLabel
~ Label IDLabel
~ Label passwordLabel
~ Label warningLabel
~ TextField editTextFieldRow
~ TextField editTextFieldColumn
+ void switchToDatabaseView()
+ void switchToDatabaseEdit()
+ {static} boolean isInteger(String)
+ {static} boolean isManager()
+ void testUsernamePassword()
+ void showData()
+ void editData(String,int)
}
class com.example.Controllers.OrderController {
- Scene scene
- Parent root
- Stage stage
~ Label IDLabel
~ RadioButton mozzButton
~ RadioButton exMozzButton
~ RadioButton cheddButton
~ RadioButton exCheddButton
~ RadioButton provButton
~ RadioButton exProvButton
~ RadioButton parmButton
~ RadioButton exParmButton
~ RadioButton pepButton
~ RadioButton exPepButton
~ RadioButton hamButton
~ RadioButton exHamButton
~ RadioButton bacButton
~ RadioButton exBacButton
~ RadioButton beefButton
~ RadioButton exBeefButton
~ RadioButton chicButton
~ RadioButton exChicButton
~ RadioButton PSButton
~ RadioButton exPSButton
~ RadioButton onionButton
~ RadioButton exOnionButton
~ RadioButton BPButton
~ RadioButton exBPButton
~ RadioButton spinButton
~ RadioButton exSpinButton
~ RadioButton tomButton
~ RadioButton exTomButton
~ RadioButton pinButton
~ RadioButton exPinButton
~ RadioButton BOButton
~ RadioButton exBOButton
~ RadioButton mushButton
~ RadioButton exMushButton
~ RadioButton banPepButton
~ RadioButton exBanPepButton
~ RadioButton jalButton
~ RadioButton exJalButton
~ RadioButton drinkSize
~ RadioButton drinkFlavor
+ {static} ArrayList<PizzaObject> pizzaArray
+ {static} ArrayList<DrinkObject> drinkArray
+ ArrayList<PizzaObject> createPizza(int,String,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean,Boolean)
+ ArrayList<DrinkObject> createDrink(String,String)
+ {static} ArrayList<DrinkObject> getDrinkArray()
+ {static} ArrayList<PizzaObject> getPizzaArray()
+ {static} void setPizzaArray(ArrayList<PizzaObject>)
+ {static} void setDrinkArray(ArrayList<DrinkObject>)
+ void switchToOrderView2()
+ void switchToOrderView3()
+ void switchToConfirmingOrdersPage()
}
class com.example.PizzaObject {
- int size
- String crustType
- Boolean hasMozzarella
- Boolean hasExtraMozzarella
- Boolean hasCheddar
- Boolean hasExtraCheddar
- Boolean hasProvolone
- Boolean hasExtraProvolone
- Boolean hasParmesean
- Boolean hasExtraParmesean
- Boolean hasPepperoni
- Boolean hasExtraPepperoni
- Boolean hasHam
- Boolean hasExtraHam
- Boolean hasBacon
- Boolean hasExtraBacon
- Boolean hasBeef
- Boolean hasExtraBeef
- Boolean hasChicken
- Boolean hasExtraChicken
- Boolean hasPhillySteak
- Boolean hasExtraPhillySteak
- Boolean hasOnion
- Boolean hasExtraOnion
- Boolean hasBellPepper
- Boolean hasExtraBellPepper
- Boolean hasSpinach
- Boolean hasExtraSpinach
- Boolean hasTomato
- Boolean hasExtraTomato
- Boolean hasPineapple
- Boolean hasExtraPineapple
- Boolean hasBlackOlives
- Boolean hasExtraBlackOlives
- Boolean hasMushrooms
- Boolean hasExtraMushrooms
- Boolean hasBananaPeppers
- Boolean hasExtraBananaPeppers
- Boolean hasJalapenos
- Boolean hasExtraJalapenos
+ Boolean getHasMozzarella()
+ Boolean getHasBacon()
+ Boolean getHasBeef()
+ Boolean getHasBellPepper()
+ Boolean getHasCheddar()
+ Boolean getHasChicken()
+ Boolean getHasExtraBacon()
+ Boolean getHasExtraBeef()
+ Boolean getHasExtraBellPepper()
+ Boolean getHasExtraCheddar()
+ Boolean getHasExtraChicken()
+ Boolean getHasExtraHam()
+ Boolean getHasExtraMozzarella()
+ Boolean getHasExtraParmesean()
+ Boolean getHasExtraOnion()
+ Boolean getHasExtraPepperoni()
+ Boolean getHasExtraPhillySteak()
+ Boolean getHasExtraProvolone()
+ Boolean getHasExtraSpinach()
+ Boolean getHasHam()
+ Boolean getHasOnion()
+ Boolean getHasParmesean()
+ Boolean getHasPepperoni()
+ Boolean getHasPhillySteak()
+ Boolean getHasProvolone()
+ int getSize()
+ String getCrustType()
+ Boolean getHasSpinach()
+ void setCrustType(String)
+ void setHasBacon(Boolean)
+ void setHasBeef(Boolean)
+ void setHasBellPepper(Boolean)
+ void setHasCheddar(Boolean)
+ void setHasChicken(Boolean)
+ void setHasExtraBacon(Boolean)
+ void setHasExtraBeef(Boolean)
+ void setHasExtraCheddar(Boolean)
+ void setHasExtraBellPepper(Boolean)
+ Boolean getHasExtraTomato()
+ Boolean getHasTomato()
+ void setHasExtraChicken(Boolean)
+ void setHasExtraHam(Boolean)
+ void setHasExtraMozzarella(Boolean)
+ void setHasExtraParmesean(Boolean)
+ void setHasExtraOnion(Boolean)
+ void setHasExtraPepperoni(Boolean)
+ Boolean getHasPineapple()
+ void setHasExtraPhillySteak(Boolean)
+ Boolean getHasExtraPineapple()
+ void setHasExtraProvolone(Boolean)
+ void setHasExtraSpinach(Boolean)
+ void setHasExtraTomato(Boolean)
+ void setHasHam(Boolean)
+ void setHasMozzarella(Boolean)
+ void setHasOnion(Boolean)
+ void setHasExtraPineapple(Boolean)
+ void setHasParmesean(Boolean)
+ void setHasPepperoni(Boolean)
+ void setHasPhillySteak(Boolean)
+ Boolean getHasBananaPeppers()
+ void setHasPineapple(Boolean)
+ Boolean getHasBlackOlives()
+ Boolean getHasExtraBlackOlives()
+ Boolean getHasExtraMushrooms()
+ Boolean getHasExtraBananaPeppers()
+ Boolean getHasExtraJalapenos()
+ Boolean getHasMushrooms()
+ Boolean getHasJalapenos()
+ void setHasBananaPeppers(Boolean)
+ void setHasBlackOlives(Boolean)
+ void setHasExtraBlackOlives(Boolean)
+ void setHasExtraBananaPeppers(Boolean)
+ void setHasExtraJalapenos(Boolean)
+ void setHasMushrooms(Boolean)
+ void setHasExtraMushrooms(Boolean)
+ void setHasJalapenos(Boolean)
+ void setHasProvolone(Boolean)
+ void setHasSpinach(Boolean)
+ void setHasTomato(Boolean)
+ void setSize(int)
}
class com.example.Database.Database {
~ String databaseURL
~ Scanner sc
+ long getNumber()
+ void addCustomer()
+ void changeCustomer()
+ void addCard()
+ void deleteCard()
+ void addOrderDetails(String,String,DeliveryInfoObject,ArrayList<PizzaObject>,ArrayList<DrinkObject>)
}
class com.example.DrinkObject {
- String size
- String flavor
}
class com.example.Controllers.StartingController {
- Stage stage
- Scene scene
- Parent root
+ void switchToEmp(ActionEvent)
+ void switchToMan(ActionEvent)
}
class com.example.Controllers.ReceiptController {
- String paymentType
- String cardNumber
- String expirationDate
- String cvv
- String nameOnCard
- String zipCode
- String cashAmount
- String changeDue
- String routingAddress
- String accountNumber
- String checkNumber
~ RadioButton paymentTypeButton
~ TextField cashTextField
~ TextField cardTextField
~ TextField expDateTextField
~ TextField cvvTextField
~ TextField nameOnCardTextField
~ TextField zipTextField
~ TextField routingAddTextField
~ TextField accNumTextField
~ TextField checkNumTextField
- Stage stage
- Parent root
- Scene scene
~ Label IDLabel
+ void switchToCardInfo()
+ void switchToCashInfo()
+ void switchToCheckInfo()
+ void switchToReceiptPage()
+ void printReceipt(ArrayList<DrinkObject>,ArrayList<PizzaObject>)
}
class com.example.Main {
+ void start(Stage)
+ {static} void main(String[])
}
class com.example.Controllers.ConfirmingOrdersController {
- Parent root
- Stage stage
- Scene scene
~ Label IDLabel
+ void rightPizzaClicked()
+ void leftPizzaClicked()
+ void switchToReceiptPage()
+ void newPizzaButton(ArrayList<PizzaObject>)
}
class com.example.Controllers.CustomerInfoPageController {
~ TextField nameTextField
~ TextField addressTextField
~ TextField deliveryTextFeild
~ RadioButton deliveryType
~ Button continueButton
}
class com.example.DeliveryInfoObject {
- String address
- String customerName
- String deliveryInfo
+ String getAddress()
+ String getCustomerName()
+ String getDeliveryInfo()
+ void setAddress(String)
+ void setCustomerName(String)
+ void setDeliveryInfo(String)
}


javafx.application.Application <|-- com.example.Main
@enduml